
version: "3.8"

# healthcheck from Vinicius Chan's answer to https://stackoverflow.com/questions/35069027/

services:
  web:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
  api:
    image: ghcr.io/seccdc/flexo:latest
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      DBADDR: "db:5432"
      DBUSER: flexo
      DBPASS: flexo
      DBNAME: FLEXO_DB_NAME
      DBSSL:  disable
      SECRET: shared_secret
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  db:
    image: postgres:13.2
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: flexo
      POSTGRES_USER: flexo
      POSTGRES_PASSWORD: flexo
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flexo"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
